from django import forms

class LatexLetterForm(forms.Form):
    sender_name = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Name'}))
    sender_streetaddress = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Street and Number'}))
    sender_zipcity = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Zip Code and City'}))
    sender_phone = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Phone Number'}))
    sender_phonename = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Phone Name'}))
    sender_email = forms.EmailField(required=False, max_length=100, widget=forms.EmailInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Email'}))
    business_myref = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'My Reference'}))
    business_yourref = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field', 'placeholder': 'Your Reference'}))
    business_yourmailfrom = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field', 'placeholder': 'Your Email From...'}))
    business_customernumber = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Customer Number'}))
    business_invoicenumber = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Invoice Number'}))
    business_place = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Business Place'}))
    business_date = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field ', 'placeholder': 'Business Date'}))
    recipient_addrfield = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control input-field ', 'placeholder': 'Receiver'}))
    content_subject = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field subject-field', 'placeholder': 'Subject'}))
    content_opening = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field', 'placeholder': 'Opening'}))
    content_text = forms.CharField(required=False, widget=forms.Textarea(attrs={'class': 'form-control input-field content-field', 'placeholder': 'Text...'}))
    content_closing = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'class': 'form-control input-field', 'placeholder': 'Closing'}))
    content_ps = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control input-field', 'placeholder': 'PS'}))
    content_enclosing = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control input-field', 'placeholder': 'Enclosing'}))
    content_cc = forms.CharField(required=False, widget=forms.TextInput(attrs={'class': 'form-control input-field', 'placeholder': 'CC'}))
